[15:41:17] INFO     Start Pynguin Test Generation…                                                                                                                                                 generator.py:106
           INFO     Collecting static constants from module under test                                                                                                                             generator.py:208
           INFO     No constants found                                                                                                                                                             generator.py:211
           INFO     Setting up runtime collection of constants                                                                                                                                     generator.py:220
           INFO     Analyzed project to create test cluster                                                                                                                                           module.py:887
           INFO     Modules:       2                                                                                                                                                                  module.py:888
           INFO     Functions:     2                                                                                                                                                                  module.py:889
           INFO     Classes:       6                                                                                                                                                                  module.py:890
           INFO     Using seed 1629381673714481067                                                                                                                                                 generator.py:194
           INFO     Using strategy: Algorithm.DYNAMOSA                                                                                                                            generationalgorithmfactory.py:267
           INFO     Instantiated 16 fitness functions                                                                                                                             generationalgorithmfactory.py:353
           INFO     Using CoverageArchive                                                                                                                                         generationalgorithmfactory.py:311
           INFO     Using selection function: Selection.TOURNAMENT_SELECTION                                                                                                      generationalgorithmfactory.py:286
           INFO     No stopping condition configured!                                                                                                                              generationalgorithmfactory.py:92
           INFO     Using fallback timeout of 600 seconds                                                                                                                          generationalgorithmfactory.py:93
           INFO     Using crossover function: SinglePointRelativeCrossOver                                                                                                        generationalgorithmfactory.py:299
           INFO     Using ranking function: RankBasedPreferenceSorting                                                                                                            generationalgorithmfactory.py:319
           INFO     Start generating test cases                                                                                                                                                    generator.py:329
[15:41:19] INFO     Initial Population, Coverage: 0.750000                                                                                                                                     searchobserver.py:66
[15:41:28] INFO     Iteration:       1, Coverage: 0.750000                                                                                                                                     searchobserver.py:70
[15:41:38] INFO     Iteration:       2, Coverage: 0.812500                                                                                                                                     searchobserver.py:70
[15:42:03] INFO     Iteration:       3, Coverage: 0.812500                                                                                                                                     searchobserver.py:70
[15:42:53] INFO     Iteration:       4, Coverage: 0.812500                                                                                                                                     searchobserver.py:70
[15:43:30] INFO     Stop Pynguin Test Generation…                                                                                                                                                  generator.py:109
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/bin/pynguin:8 in <module>   │
│                                                                                                  │
│   5 from pynguin.cli import main                                                                 │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/cli.py:190 in main                                                                     │
│                                                                                                  │
│   187 │   set_configuration(parsed.config)                                                       │
│   188 │   if console is not None:                                                                │
│   189 │   │   with console.status("Running Pynguin..."):                                         │
│ ❱ 190 │   │   │   return run_pynguin().value                                                     │
│   191 │   else:                                                                                  │
│   192 │   │   return run_pynguin().value                                                         │
│   193                                                                                            │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/generator.py:107 in run_pynguin                                                        │
│                                                                                                  │
│   104 │   """                                                                                    │
│   105 │   try:                                                                                   │
│   106 │   │   _LOGGER.info("Start Pynguin Test Generation…")                                     │
│ ❱ 107 │   │   return _run()                                                                      │
│   108 │   finally:                                                                               │
│   109 │   │   _LOGGER.info("Stop Pynguin Test Generation…")                                      │
│   110                                                                                            │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/generator.py:330 in _run                                                               │
│                                                                                                  │
│   327 │   │   executor, test_cluster, constant_provider                                          │
│   328 │   )                                                                                      │
│   329 │   _LOGGER.info("Start generating test cases")                                            │
│ ❱ 330 │   generation_result = algorithm.generate_tests()                                         │
│   331 │   if algorithm.resources_left():                                                         │
│   332 │   │   _LOGGER.info("Algorithm stopped before using all resources.")                      │
│   333 │   else:                                                                                  │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/generation/algorithms/dynamosastrategy.py:70 in generate_tests                         │
│                                                                                                  │
│    67 │   │   │   self.create_test_suite(self._archive.solutions)                                │
│    68 │   │   )                                                                                  │
│    69 │   │   while self.resources_left() and len(self._archive.uncovered_goals) > 0:            │
│ ❱  70 │   │   │   self.evolve()                                                                  │
│    71 │   │   │   self.after_search_iteration(self.create_test_suite(self._archive.solutions))   │
│    72 │   │                                                                                      │
│    73 │   │   self.after_search_finish()                                                         │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/generation/algorithms/dynamosastrategy.py:94 in evolve                                 │
│                                                                                                  │
│    91 │   │   # Ranking the union                                                                │
│    92 │   │   self._logger.debug("Union Size = %d", len(union))                                  │
│    93 │   │   # Ranking the union using the best rank algorithm                                  │
│ ❱  94 │   │   fronts = self._ranking_function.compute_ranking_assignment(                        │
│    95 │   │   │   union, self._goals_manager.current_goals                                       │
│    96 │   │   )                                                                                  │
│    97                                                                                            │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/operators/ranking/rankingfunction.py:106 in compute_ranking_assignment              │
│                                                                                                  │
│   103 │   │                                                                                      │
│   104 │   │   # First apply the "preference sorting" to the first front only then compute        │
│   105 │   │   # the ranks according to the non-dominate sorting algorithm                        │
│ ❱ 106 │   │   zero_front: list[C] = self._get_zero_front(solutions, uncovered_goals)             │
│   107 │   │   fronts.append(zero_front)                                                          │
│   108 │   │   front_index = 1                                                                    │
│   109                                                                                            │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/operators/ranking/rankingfunction.py:159 in _get_zero_front                         │
│                                                                                                  │
│   156 │   │   │   )                                                                              │
│   157 │   │   │   best: C | None = None                                                          │
│   158 │   │   │   for solution in solutions:                                                     │
│ ❱ 159 │   │   │   │   flag = comparator.compare(solution, best)                                  │
│   160 │   │   │   │   if flag < 0 or (flag == 0 and randomness.next_bool()):                     │
│   161 │   │   │   │   │   best = solution                                                        │
│   162 │   │   │   assert best is not None                                                        │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/comparators/preferencesortingcomparator.py:48 in compare                            │
│                                                                                                  │
│   45 │   │   if solution_2 is None:                                                              │
│   46 │   │   │   return -1                                                                       │
│   47 │   │                                                                                       │
│ ❱ 48 │   │   value_1 = solution_1.get_fitness_for(self._objective)                               │
│   49 │   │   value_2 = solution_2.get_fitness_for(self._objective)                               │
│   50 │   │   if value_1 < value_2:                                                               │
│   51 │   │   │   return -1                                                                       │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/chromosome.py:128 in get_fitness_for                                                │
│                                                                                                  │
│   125 │   │   Returns:                                                                           │
│   126 │   │   │   Its fitness value                                                              │
│   127 │   │   """                                                                                │
│ ❱ 128 │   │   return self._computation_cache.get_fitness_for(fitness_function)                   │
│   129 │                                                                                          │
│   130 │   def get_is_covered(self, fitness_function: ff.FitnessFunction) -> bool:                │
│   131 │   │   """Check if the individual covers this fitness function.                           │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/computations.py:493 in get_fitness_for                                              │
│                                                                                                  │
│   490 │   │   Returns:                                                                           │
│   491 │   │   │   Its fitness value                                                              │
│   492 │   │   """                                                                                │
│ ❱ 493 │   │   self._check_cache(                                                                 │
│   494 │   │   │   self._compute_fitness,                                                         │
│   495 │   │   │   self._fitness_cache,                                                           │
│   496 │   │   │   self._fitness_functions,                                                       │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/computations.py:426 in _check_cache                                                 │
│                                                                                                  │
│   423 │   │   │   # If the chromosome has changed, we invalidate all values computed so far      │
│   424 │   │   │   self.invalidate_cache()                                                        │
│   425 │   │   │   # Compute those values in which we are interested.                             │
│ ❱ 426 │   │   │   comp(only)                                                                     │
│   427 │   │   │   # Mark individual as no longer changed.                                        │
│   428 │   │   │   self._chromosome.set_changed(False)                                            │
│   429 │   │   elif len(cache) != len(funcs):                                                     │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/computations.py:437 in _compute_fitness                                             │
│                                                                                                  │
│   434 │   def _compute_fitness(self, only: FitnessFunction | None = None):                       │
│   435 │   │   for fitness_func in self._fitness_functions if only is None else (only,):          │
│   436 │   │   │   if fitness_func not in self._fitness_cache:                                    │
│ ❱ 437 │   │   │   │   new_value = fitness_func.compute_fitness(self._chromosome)                 │
│   438 │   │   │   │   assert (                                                                   │
│   439 │   │   │   │   │   not math.isnan(new_value)                                              │
│   440 │   │   │   │   │   and not math.isinf(new_value)                                          │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/coverage/branchgoals.py:305 in compute_fitness                                         │
│                                                                                                  │
│   302 │   │   self._goal = goal                                                                  │
│   303 │                                                                                          │
│   304 │   def compute_fitness(self, individual: tcc.TestCaseChromosome) -> float:                │
│ ❱ 305 │   │   result = self._run_test_case_chromosome(individual)                                │
│   306 │   │                                                                                      │
│   307 │   │   distance = self._goal.get_distance(result, self._executor.tracer)                  │
│   308 │   │   return distance.get_resulting_branch_fitness()                                     │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/ga/computations.py:48 in _run_test_case_chromosome                                     │
│                                                                                                  │
│    45 │   │   """                                                                                │
│    46 │   │   if individual.has_changed() or individual.get_last_execution_result() is None:     │
│    47 │   │   │   individual.set_last_execution_result(                                          │
│ ❱  48 │   │   │   │   self._executor.execute(individual.test_case)                               │
│    49 │   │   │   )                                                                              │
│    50 │   │   │   individual.set_changed(False)                                                  │
│    51 │   │   result = individual.get_last_execution_result()                                    │
│                                                                                                  │
│ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-package │
│ s/pynguin/testcase/execution.py:1277 in execute                                                  │
│                                                                                                  │
│   1274 │   │   │   │   )                                                                         │
│   1275 │   │   │   │   thread.start()                                                            │
│   1276 │   │   │   │   # Set a timeout for the thread execution of at most 5 seconds.            │
│ ❱ 1277 │   │   │   │   thread.join(timeout=min(5, len(test_case.statements)))                    │
│   1278 │   │   │   │   if thread.is_alive():                                                     │
│   1279 │   │   │   │   │   # Set thread ident to invalid value, such that the tracer             │
│   1280 │   │   │   │   │   # kills the thread                                                    │
│                                                                                                  │
│ /usr/lib/python3.10/threading.py:1093 in join                                                    │
│                                                                                                  │
│   1090 │   │   else:                                                                             │
│   1091 │   │   │   # the behavior of a negative timeout isn't documented, but                    │
│   1092 │   │   │   # historically .join(timeout=x) for x<0 has acted as if timeout=0             │
│ ❱ 1093 │   │   │   self._wait_for_tstate_lock(timeout=max(timeout, 0))                           │
│   1094 │                                                                                         │
│   1095 │   def _wait_for_tstate_lock(self, block=True, timeout=-1):                              │
│   1096 │   │   # Issue #18808: wait for the thread state to be gone.                             │
│                                                                                                  │
│ /usr/lib/python3.10/threading.py:1109 in _wait_for_tstate_lock                                   │
│                                                                                                  │
│   1106 │   │   │   return                                                                        │
│   1107 │   │                                                                                     │
│   1108 │   │   try:                                                                              │
│ ❱ 1109 │   │   │   if lock.acquire(block, timeout):                                              │
│   1110 │   │   │   │   lock.release()                                                            │
│   1111 │   │   │   │   self._stop()                                                              │
│   1112 │   │   except:                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyboardInterrupt

(venv)  ✘ user  thesis/Test-generation-with-Pynguin   main  pynguin --module-name queue_example --project-path . --output-path . --seed 1629381673714481067 -v
[15:44:12] INFO     Start Pynguin Test Generation…                                                                                                                                                 generator.py:106
           INFO     Collecting static constants from module under test                                                                                                                             generator.py:208
           INFO     No constants found                                                                                                                                                             generator.py:211
           INFO     Setting up runtime collection of constants                                                                                                                                     generator.py:220
           INFO     Analyzed project to create test cluster                                                                                                                                           module.py:887
           INFO     Modules:       2                                                                                                                                                                  module.py:888
           INFO     Functions:     2                                                                                                                                                                  module.py:889
           INFO     Classes:       6                                                                                                                                                                  module.py:890
           INFO     Using seed 1629381673714481067                                                                                                                                                 generator.py:194
           INFO     Using strategy: Algorithm.DYNAMOSA                                                                                                                            generationalgorithmfactory.py:267
           INFO     Instantiated 16 fitness functions                                                                                                                             generationalgorithmfactory.py:353
           INFO     Using CoverageArchive                                                                                                                                         generationalgorithmfactory.py:311
           INFO     Using selection function: Selection.TOURNAMENT_SELECTION                                                                                                      generationalgorithmfactory.py:286
           INFO     No stopping condition configured!                                                                                                                              generationalgorithmfactory.py:92
           INFO     Using fallback timeout of 600 seconds                                                                                                                          generationalgorithmfactory.py:93
           INFO     Using crossover function: SinglePointRelativeCrossOver                                                                                                        generationalgorithmfactory.py:299
           INFO     Using ranking function: RankBasedPreferenceSorting                                                                                                            generationalgorithmfactory.py:319
           INFO     Start generating test cases                                                                                                                                                    generator.py:329
[15:44:14] INFO     Initial Population, Coverage: 0.750000                                                                                                                                     searchobserver.py:66
[15:44:23] INFO     Iteration:       1, Coverage: 0.750000                                                                                                                                     searchobserver.py:70
[15:44:33] INFO     Iteration:       2, Coverage: 0.812500                                                                                                                                     searchobserver.py:70
[15:44:58] INFO     Iteration:       3, Coverage: 0.812500                                                                                                                                     searchobserver.py:70
[15:45:48] INFO     Iteration:       4, Coverage: 0.812500                                                                                                                                     searchobserver.py:70
[15:46:38] INFO     Iteration:       5, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:47:37] INFO     Iteration:       6, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:48:15] INFO     Iteration:       7, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:49:01] INFO     Iteration:       8, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:49:48] INFO     Iteration:       9, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:50:38] INFO     Iteration:      10, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:51:24] INFO     Iteration:      11, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:52:09] INFO     Iteration:      12, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:52:59] INFO     Iteration:      13, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:54:01] INFO     Iteration:      14, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
[15:54:53] INFO     Iteration:      15, Coverage: 0.875000                                                                                                                                     searchobserver.py:70
           INFO     Stopping condition reached                                                                                                                                                     generator.py:334
           INFO     Used search time: 641/600                                                                                                                                                      generator.py:336
           INFO     Stop generating test cases                                                                                                                                                     generator.py:337
           INFO     Start generating assertions                                                                                                                                                    generator.py:358
           INFO     Setup mutation controller                                                                                                                                                 mutationadapter.py:68
           INFO     Build AST for queue_example                                                                                                                                               mutationadapter.py:54
           INFO     Mutate module queue_example                                                                                                                                               mutationadapter.py:56
           ERROR    Exception in Thread: <Thread(Thread-722 (place_order), started 140631993218624)>                                                                                              execution.py:1214
                    ╭──────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────╮                  
                    │ /usr/lib/python3.10/threading.py:1009 in _bootstrap_inner                                                                                                                 │                  
                    │                                                                                                                                                                           │                  
                    │   1006 │   │   │   │   _sys.setprofile(_profile_hook)                                                                                                                     │                  
                    │   1007 │   │   │                                                                                                                                                          │                  
                    │   1008 │   │   │   try:                                                                                                                                                   │                  
                    │ ❱ 1009 │   │   │   │   self.run()                                                                                                                                         │                  
                    │   1010 │   │   │   except:                                                                                                                                                │                  
                    │   1011 │   │   │   │   self._invoke_excepthook(self)                                                                                                                      │                  
                    │   1012 │   │   finally:                                                                                                                                                   │                  
                    │                                                                                                                                                                           │                  
                    │ /usr/lib/python3.10/threading.py:946 in run                                                                                                                               │                  
                    │                                                                                                                                                                           │                  
                    │    943 │   │   """                                                                                                                                                        │                  
                    │    944 │   │   try:                                                                                                                                                       │                  
                    │    945 │   │   │   if self._target is not None:                                                                                                                           │                  
                    │ ❱  946 │   │   │   │   self._target(*self._args, **self._kwargs)                                                                                                          │                  
                    │    947 │   │   finally:                                                                                                                                                   │                  
                    │    948 │   │   │   # Avoid a refcycle if the thread is running a function with                                                                                            │                  
                    │    949 │   │   │   # an argument that has a member that points to the thread.                                                                                             │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example:26 in place_order                                                                           │                  
                    │                                                                                                                                                                           │                  
                    │ [Errno 2] No such file or directory: '/home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example'                                                      │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-packages/pynguin/testcase/execution.py:734 in executed_code_object               │                  
                    │                                                                                                                                                                           │                  
                    │    731 │   │   │   RuntimeError: raised when called from another thread                                                                                                   │                  
                    │    732 │   │   """                                                                                                                                                        │                  
                    │    733 │   │   if threading.current_thread().ident != self._current_thread_identifier:                                                                                    │                  
                    │ ❱  734 │   │   │   raise RuntimeError(                                                                                                                                    │                  
                    │    735 │   │   │   │   "The current thread shall not be executed any more, thus I kill it."                                                                               │                  
                    │    736 │   │   │   )                                                                                                                                                      │                  
                    │    737                                                                                                                                                                    │                  
                    ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  
                    RuntimeError: The current thread shall not be executed any more, thus I kill it.                                                                                                               
[15:54:54] ERROR    Exception in Thread: <Thread(Thread-723 (serve_order), started 140631993218624)>                                                                                              execution.py:1214
                    ╭──────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────╮                  
                    │ /usr/lib/python3.10/threading.py:1009 in _bootstrap_inner                                                                                                                 │                  
                    │                                                                                                                                                                           │                  
                    │   1006 │   │   │   │   _sys.setprofile(_profile_hook)                                                                                                                     │                  
                    │   1007 │   │   │                                                                                                                                                          │                  
                    │   1008 │   │   │   try:                                                                                                                                                   │                  
                    │ ❱ 1009 │   │   │   │   self.run()                                                                                                                                         │                  
                    │   1010 │   │   │   except:                                                                                                                                                │                  
                    │   1011 │   │   │   │   self._invoke_excepthook(self)                                                                                                                      │                  
                    │   1012 │   │   finally:                                                                                                                                                   │                  
                    │                                                                                                                                                                           │                  
                    │ /usr/lib/python3.10/threading.py:946 in run                                                                                                                               │                  
                    │                                                                                                                                                                           │                  
                    │    943 │   │   """                                                                                                                                                        │                  
                    │    944 │   │   try:                                                                                                                                                       │                  
                    │    945 │   │   │   if self._target is not None:                                                                                                                           │                  
                    │ ❱  946 │   │   │   │   self._target(*self._args, **self._kwargs)                                                                                                          │                  
                    │    947 │   │   finally:                                                                                                                                                   │                  
                    │    948 │   │   │   # Avoid a refcycle if the thread is running a function with                                                                                            │                  
                    │    949 │   │   │   # an argument that has a member that points to the thread.                                                                                             │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example:33 in serve_order                                                                           │                  
                    │                                                                                                                                                                           │                  
                    │ [Errno 2] No such file or directory: '/home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example'                                                      │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-packages/pynguin/testcase/execution.py:734 in executed_code_object               │                  
                    │                                                                                                                                                                           │                  
                    │    731 │   │   │   RuntimeError: raised when called from another thread                                                                                                   │                  
                    │    732 │   │   """                                                                                                                                                        │                  
                    │    733 │   │   if threading.current_thread().ident != self._current_thread_identifier:                                                                                    │                  
                    │ ❱  734 │   │   │   raise RuntimeError(                                                                                                                                    │                  
                    │    735 │   │   │   │   "The current thread shall not be executed any more, thus I kill it."                                                                               │                  
                    │    736 │   │   │   )                                                                                                                                                      │                  
                    │    737                                                                                                                                                                    │                  
                    ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  
                    RuntimeError: The current thread shall not be executed any more, thus I kill it.                                                                                                               
Time taken:  1.3228857517242432
[15:54:56] ERROR    Exception in Thread: <Thread(Thread-724 (place_order), started 140631993218624)>                                                                                              execution.py:1214
                    ╭──────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────╮                  
                    │ /usr/lib/python3.10/threading.py:1009 in _bootstrap_inner                                                                                                                 │                  
                    │                                                                                                                                                                           │                  
                    │   1006 │   │   │   │   _sys.setprofile(_profile_hook)                                                                                                                     │                  
                    │   1007 │   │   │                                                                                                                                                          │                  
                    │   1008 │   │   │   try:                                                                                                                                                   │                  
                    │ ❱ 1009 │   │   │   │   self.run()                                                                                                                                         │                  
                    │   1010 │   │   │   except:                                                                                                                                                │                  
                    │   1011 │   │   │   │   self._invoke_excepthook(self)                                                                                                                      │                  
                    │   1012 │   │   finally:                                                                                                                                                   │                  
                    │                                                                                                                                                                           │                  
                    │ /usr/lib/python3.10/threading.py:946 in run                                                                                                                               │                  
                    │                                                                                                                                                                           │                  
                    │    943 │   │   """                                                                                                                                                        │                  
                    │    944 │   │   try:                                                                                                                                                       │                  
                    │    945 │   │   │   if self._target is not None:                                                                                                                           │                  
                    │ ❱  946 │   │   │   │   self._target(*self._args, **self._kwargs)                                                                                                          │                  
                    │    947 │   │   finally:                                                                                                                                                   │                  
                    │    948 │   │   │   # Avoid a refcycle if the thread is running a function with                                                                                            │                  
                    │    949 │   │   │   # an argument that has a member that points to the thread.                                                                                             │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example:26 in place_order                                                                           │                  
                    │                                                                                                                                                                           │                  
                    │ [Errno 2] No such file or directory: '/home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example'                                                      │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-packages/pynguin/testcase/execution.py:734 in executed_code_object               │                  
                    │                                                                                                                                                                           │                  
                    │    731 │   │   │   RuntimeError: raised when called from another thread                                                                                                   │                  
                    │    732 │   │   """                                                                                                                                                        │                  
                    │    733 │   │   if threading.current_thread().ident != self._current_thread_identifier:                                                                                    │                  
                    │ ❱  734 │   │   │   raise RuntimeError(                                                                                                                                    │                  
                    │    735 │   │   │   │   "The current thread shall not be executed any more, thus I kill it."                                                                               │                  
                    │    736 │   │   │   )                                                                                                                                                      │                  
                    │    737                                                                                                                                                                    │                  
                    ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  
                    RuntimeError: The current thread shall not be executed any more, thus I kill it.                                                                                                               
[15:54:57] ERROR    Exception in Thread: <Thread(Thread-725 (serve_order), started 140631993218624)>                                                                                              execution.py:1214
                    ╭──────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────╮                  
                    │ /usr/lib/python3.10/threading.py:1009 in _bootstrap_inner                                                                                                                 │                  
                    │                                                                                                                                                                           │                  
                    │   1006 │   │   │   │   _sys.setprofile(_profile_hook)                                                                                                                     │                  
                    │   1007 │   │   │                                                                                                                                                          │                  
                    │   1008 │   │   │   try:                                                                                                                                                   │                  
                    │ ❱ 1009 │   │   │   │   self.run()                                                                                                                                         │                  
                    │   1010 │   │   │   except:                                                                                                                                                │                  
                    │   1011 │   │   │   │   self._invoke_excepthook(self)                                                                                                                      │                  
                    │   1012 │   │   finally:                                                                                                                                                   │                  
                    │                                                                                                                                                                           │                  
                    │ /usr/lib/python3.10/threading.py:946 in run                                                                                                                               │                  
                    │                                                                                                                                                                           │                  
                    │    943 │   │   """                                                                                                                                                        │                  
                    │    944 │   │   try:                                                                                                                                                       │                  
                    │    945 │   │   │   if self._target is not None:                                                                                                                           │                  
                    │ ❱  946 │   │   │   │   self._target(*self._args, **self._kwargs)                                                                                                          │                  
                    │    947 │   │   finally:                                                                                                                                                   │                  
                    │    948 │   │   │   # Avoid a refcycle if the thread is running a function with                                                                                            │                  
                    │    949 │   │   │   # an argument that has a member that points to the thread.                                                                                             │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example:33 in serve_order                                                                           │                  
                    │                                                                                                                                                                           │                  
                    │ [Errno 2] No such file or directory: '/home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/queue_example'                                                      │                  
                    │                                                                                                                                                                           │                  
                    │ /home/user/Downloads/Ashfaq/thesis/Test-generation-with-Pynguin/venv/lib/python3.10/site-packages/pynguin/testcase/execution.py:734 in executed_code_object               │                  
                    │                                                                                                                                                                           │                  
                    │    731 │   │   │   RuntimeError: raised when called from another thread                                                                                                   │                  
                    │    732 │   │   """                                                                                                                                                        │                  
                    │    733 │   │   if threading.current_thread().ident != self._current_thread_identifier:                                                                                    │                  
                    │ ❱  734 │   │   │   raise RuntimeError(                                                                                                                                    │                  
                    │    735 │   │   │   │   "The current thread shall not be executed any more, thus I kill it."                                                                               │                  
                    │    736 │   │   │   )                                                                                                                                                      │                  
                    │    737                                                                                                                                                                    │                  
                    ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  
                    RuntimeError: The current thread shall not be executed any more, thus I kill it.                                                                                                               
Time taken:  1.2180719375610352
           INFO     Generated 37 mutants                                                                                                                                                      mutationadapter.py:64
[15:55:09] INFO     Running tests on mutant   1/37                                                                                                                                        assertiongenerator.py:223
[15:55:15] INFO     Running tests on mutant   2/37                                                                                                                                        assertiongenerator.py:223
           INFO     Running tests on mutant   3/37                                                                                                                                        assertiongenerator.py:223
           INFO     Running tests on mutant   4/37                                                                                                                                        assertiongenerator.py:223
[15:55:21] INFO     Running tests on mutant   5/37                                                                                                                                        assertiongenerator.py:223
[15:55:25] INFO     Running tests on mutant   6/37                                                                                                                                        assertiongenerator.py:223
[15:55:31] INFO     Running tests on mutant   7/37                                                                                                                                        assertiongenerator.py:223
[15:55:37] INFO     Running tests on mutant   8/37                                                                                                                                        assertiongenerator.py:223
[15:55:43] INFO     Running tests on mutant   9/37                                                                                                                                        assertiongenerator.py:223
[15:55:49] INFO     Running tests on mutant  10/37                                                                                                                                        assertiongenerator.py:223
[15:55:55] INFO     Running tests on mutant  11/37                                                                                                                                        assertiongenerator.py:223
[15:55:57] INFO     Running tests on mutant  12/37                                                                                                                                        assertiongenerator.py:223
[15:56:04] INFO     Running tests on mutant  13/37                                                                                                                                        assertiongenerator.py:223
[15:56:10] INFO     Running tests on mutant  14/37                                                                                                                                        assertiongenerator.py:223
           INFO     Running tests on mutant  15/37                                                                                                                                        assertiongenerator.py:223
[15:56:24] INFO     Running tests on mutant  16/37                                                                                                                                        assertiongenerator.py:223
[15:56:30] INFO     Running tests on mutant  17/37                                                                                                                                        assertiongenerator.py:223
[15:56:36] INFO     Running tests on mutant  18/37                                                                                                                                        assertiongenerator.py:223
[15:56:42] INFO     Running tests on mutant  19/37                                                                                                                                        assertiongenerator.py:223
[15:56:48] INFO     Running tests on mutant  20/37                                                                                                                                        assertiongenerator.py:223
[15:56:54] INFO     Running tests on mutant  21/37                                                                                                                                        assertiongenerator.py:223
[15:57:00] INFO     Running tests on mutant  22/37                                                                                                                                        assertiongenerator.py:223
[15:57:06] INFO     Running tests on mutant  23/37                                                                                                                                        assertiongenerator.py:223
[15:57:12] INFO     Running tests on mutant  24/37                                                                                                                                        assertiongenerator.py:223
[15:57:18] INFO     Running tests on mutant  25/37                                                                                                                                        assertiongenerator.py:223
[15:57:24] INFO     Running tests on mutant  26/37                                                                                                                                        assertiongenerator.py:223
[15:57:30] INFO     Running tests on mutant  27/37                                                                                                                                        assertiongenerator.py:223
[15:57:36] INFO     Running tests on mutant  28/37                                                                                                                                        assertiongenerator.py:223
[15:57:42] INFO     Running tests on mutant  29/37                                                                                                                                        assertiongenerator.py:223
[15:57:48] INFO     Running tests on mutant  30/37                                                                                                                                        assertiongenerator.py:223
[15:57:54] INFO     Running tests on mutant  31/37                                                                                                                                        assertiongenerator.py:223
[15:57:58] INFO     Running tests on mutant  32/37                                                                                                                                        assertiongenerator.py:223
[15:58:04] INFO     Running tests on mutant  33/37                                                                                                                                        assertiongenerator.py:223
[15:58:05] INFO     Running tests on mutant  34/37                                                                                                                                        assertiongenerator.py:223
           INFO     Running tests on mutant  35/37                                                                                                                                        assertiongenerator.py:223
[15:58:11] INFO     Running tests on mutant  36/37                                                                                                                                        assertiongenerator.py:223
[15:58:17] INFO     Running tests on mutant  37/37                                                                                                                                        assertiongenerator.py:223
           INFO     Mutant 1 killed by Test(s): 2, 8, 9                                                                                                                                   assertiongenerator.py:267
           INFO     Mutant 2 killed by Test(s): 2, 9                                                                                                                                      assertiongenerator.py:267
           INFO     Mutant 3 killed by Test(s): 1, 2, 3, 4, 5, 6, 7, 8, 9                                                                                                                 assertiongenerator.py:267
           INFO     Mutant 4 killed by Test(s): 2, 4, 6, 7, 8, 9                                                                                                                          assertiongenerator.py:267
           INFO     Mutant 8 killed by Test(s): 8                                                                                                                                         assertiongenerator.py:267
           INFO     Mutant 9 killed by Test(s): 8                                                                                                                                         assertiongenerator.py:267
           INFO     Mutant 10 killed by Test(s): 2, 9                                                                                                                                     assertiongenerator.py:267
           INFO     Mutant 13 timed out. First time with test 9.                                                                                                                          assertiongenerator.py:273
           INFO     Mutant 30 killed by Test(s): 9                                                                                                                                        assertiongenerator.py:267
           INFO     Mutant 32 killed by Test(s): 2, 4, 6, 7, 8, 9                                                                                                                         assertiongenerator.py:267
           INFO     Mutant 33 killed by Test(s): 2, 9                                                                                                                                     assertiongenerator.py:267
           INFO     Mutant 34 killed by Test(s): 1, 2, 3, 4, 5, 6, 7, 8, 9                                                                                                                assertiongenerator.py:267
           INFO     Mutant 35 killed by Test(s): 0                                                                                                                                        assertiongenerator.py:267
           INFO     Mutant 36 killed by Test(s): 2, 9                                                                                                                                     assertiongenerator.py:267
           INFO     Surviving Mutant(s): 23 (Nums: 0, 5, 6, 7, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31)                                                assertiongenerator.py:280
           INFO     Written 10 test cases to ./test_queue_example.py                                                                                                                               generator.py:483
           INFO     Writing statistics                                                                                                                                                            statistics.py:354
           INFO     Stop Pynguin Test Generation… 